export * from './app_pay';
export * from './decrypt';
export * from './html5_pay';
export * from './interface/app_pay.interface';
export * from './interface/decrypt.interface';
export * from './interface/html5_pay.interface';
export * from './interface/javascript_api_pay.interface';
export * from './interface/public_key_certificate.interface';
export * from './interface/request.interface';
export * from './interface/show_pay.interface';
export * from './interface/token.interface';
export * from './interface/we_chat_pay.interface';
export * from './javascript_api_pay';
export * from './public_key_certificate';
export * from './request';
export * from './show_pay';
export * from './token';
export {weChatPay};
import {weChatPay as relWeChatPay} from './we_chat_pay';

const weChatPay = relWeChatPay;
